server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/candelariaDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  application:
    name: projectIngenieria

  mail:
    host: smtp.gmail.com
    port: 587
    username: ingenieriasoftware06@gmail.com
    password: ndkj znpt redq xpur
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    projectIngenieria: DEBUG
