server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/candelariaDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  application:
    name: projectIngenieria



logging:
  level:
    root: INFO
    projectIngenieria: DEBUG
